spring.application.name=ecommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce2
spring.datasource.username=postgres
spring.datasource.password=aldair2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.springframework.web=DEBUG

